version: "3.3"

services:
  some-service:
    image: 'spuxx/some-image:some-tag'
    restart: unless-stopped
    depends_on:
      - some-mariadb
    networks:
      - default
      - npm
    env_file:
      .env
    command: npm run start:prod

  some-mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: data
    env_file:
      .env
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - default
      - db

networks:
  default:
  npm:
    external: true
  db:
    external: true
